// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia;

#nullable disable

namespace Persistencia.Data.Migrations
{
    [DbContext(typeof(AppPruebaContext))]
    [Migration("20230818134825_InitialMigrationsCreate")]
    partial class InitialMigrationsCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dominio.Entities.Alquiler", b =>
                {
                    b.Property<int>("ID_Alquiler")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Costo_Total")
                        .HasColumnType("decimal(10.2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Automovil")
                        .HasColumnType("int");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.HasKey("ID_Alquiler");

                    b.HasIndex("ID_Automovil");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("Alquiler", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Automovil", b =>
                {
                    b.Property<int>("ID_Automovil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Capasidad")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Precio_decimal")
                        .HasColumnType("decimal(10.2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_Automovil");

                    b.ToTable("Automovil", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Cliente", b =>
                {
                    b.Property<int>("ID_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID_Cliente");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Empleado", b =>
                {
                    b.Property<int>("ID_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID_Empleado");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Registro_devolucion", b =>
                {
                    b.Property<int>("ID_Registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Combustible_Devuelto")
                        .HasColumnType("decimal(5.2)");

                    b.Property<DateTime>("Fecha_Devolucion")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Alquiler")
                        .HasColumnType("int");

                    b.Property<int>("ID_Empleado")
                        .HasColumnType("int");

                    b.Property<int>("Kilometraje_Devuelto")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto_Adicional")
                        .HasColumnType("decimal(10.2)");

                    b.HasKey("ID_Registro");

                    b.HasIndex("ID_Alquiler");

                    b.HasIndex("ID_Empleado");

                    b.ToTable("Registro_devolucion", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Registro_entrega", b =>
                {
                    b.Property<int>("ID_Registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Combustible_Entregado")
                        .HasColumnType("decimal(5.2)");

                    b.Property<DateTime>("Fecha_Entrega")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Alquiler")
                        .HasColumnType("int");

                    b.Property<int>("ID_Empleado")
                        .HasColumnType("int");

                    b.Property<int>("Kilometraje_Entregado")
                        .HasColumnType("int");

                    b.HasKey("ID_Registro");

                    b.HasIndex("ID_Alquiler");

                    b.HasIndex("ID_Empleado");

                    b.ToTable("Registro_entrega", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Reserva", b =>
                {
                    b.Property<int>("ID_Reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EStado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_Reserva")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Automovil")
                        .HasColumnType("int");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.HasKey("ID_Reserva");

                    b.HasIndex("ID_Automovil");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Sucursal", b =>
                {
                    b.Property<int>("ID_Sucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID_Sucursal");

                    b.ToTable("Sucursal", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Sucursal_automovil", b =>
                {
                    b.Property<int>("ID_Sucursal")
                        .HasColumnType("int");

                    b.Property<int>("ID_Automovil")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad_Disponible")
                        .HasColumnType("int");

                    b.HasKey("ID_Sucursal", "ID_Automovil");

                    b.HasIndex("ID_Automovil");

                    b.ToTable("Sucursal_automovil", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Alquiler", b =>
                {
                    b.HasOne("Dominio.Entities.Automovil", "Automovil")
                        .WithMany("Alquileres")
                        .HasForeignKey("ID_Automovil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Cliente", "Cliente")
                        .WithMany("Alquileres")
                        .HasForeignKey("ID_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automovil");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Dominio.Entities.Registro_devolucion", b =>
                {
                    b.HasOne("Dominio.Entities.Alquiler", "Alquiler")
                        .WithMany("Registros_devoluciones")
                        .HasForeignKey("ID_Alquiler")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Empleado", "Empleado")
                        .WithMany("Registros_Devoluciones")
                        .HasForeignKey("ID_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Dominio.Entities.Registro_entrega", b =>
                {
                    b.HasOne("Dominio.Entities.Alquiler", "Alquiler")
                        .WithMany("Registros_entregas")
                        .HasForeignKey("ID_Alquiler")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Empleado", "Empleado")
                        .WithMany("Registros_Entregas")
                        .HasForeignKey("ID_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Dominio.Entities.Reserva", b =>
                {
                    b.HasOne("Dominio.Entities.Automovil", "Automovil")
                        .WithMany("Reservas")
                        .HasForeignKey("ID_Automovil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ID_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automovil");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Dominio.Entities.Sucursal_automovil", b =>
                {
                    b.HasOne("Dominio.Entities.Automovil", "Automovil")
                        .WithMany("Sucursales_automoviles")
                        .HasForeignKey("ID_Automovil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Sucursal", "Sucursal")
                        .WithMany("Sucursales_automoviles")
                        .HasForeignKey("ID_Sucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automovil");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Dominio.Entities.Alquiler", b =>
                {
                    b.Navigation("Registros_devoluciones");

                    b.Navigation("Registros_entregas");
                });

            modelBuilder.Entity("Dominio.Entities.Automovil", b =>
                {
                    b.Navigation("Alquileres");

                    b.Navigation("Reservas");

                    b.Navigation("Sucursales_automoviles");
                });

            modelBuilder.Entity("Dominio.Entities.Cliente", b =>
                {
                    b.Navigation("Alquileres");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Dominio.Entities.Empleado", b =>
                {
                    b.Navigation("Registros_Devoluciones");

                    b.Navigation("Registros_Entregas");
                });

            modelBuilder.Entity("Dominio.Entities.Sucursal", b =>
                {
                    b.Navigation("Sucursales_automoviles");
                });
#pragma warning restore 612, 618
        }
    }
}
